service1:
  image:
    repository: ghcr.io/atlanhq/service1-main
    tag: 962c40b67130
service2:
  image:
    repository: ghcr.io/atlanhq/service2-main
    tag: 3e035a0fe048
service3:
  image:
    repository: ghcr.io/atlanhq/service3-main
    tag: 779a77dba2d3
service4:
  image:
    repository: ghcr.io/atlanhq/service4-main
    tag: 216102333bea
