name: Check PR Template

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check_pr_template:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_PAT }}
          fetch-depth: 0

      - name: Read PR template file
        id: read_template
        run: |
          PR_TEMPLATE_FILE=".github/pull_request_template.md"
          if [ -f "$PR_TEMPLATE_FILE" ]; then
            echo "::set-output name=template::$(cat "$PR_TEMPLATE_FILE")"
          fi
        
      - name: Display template content
        run: |
          echo "Template: ${{ steps.read_template.outputs.template }}"

      - name: Check and Update PR Body
        id: check_and_update
        run: |
          PR_BODY=$(cat "$GITHUB_EVENT_PATH" | jq -r .pull_request.body)
          PR_TEMPLATE="${{ steps.read_template.outputs.template }}"

          # Check if the PR body includes the template content
          if [[ ! "$PR_BODY" =~ "$PR_TEMPLATE" ]]; then
            # Add template content to the top of the PR body
            NEW_PR_BODY="$PR_TEMPLATE$PR_BODY"
            jq -n --arg new_body "$NEW_PR_BODY" '{"body":$new_body}' > updated_pr_body.json
            mv updated_pr_body.json "$GITHUB_EVENT_PATH"
            echo "Updated PR body with missing template fields."
          fi

      - name: Update PR
        if: steps.check_and_update.outputs.body_changed == 'true'
        run: gh pr edit ${{ github.event.number }} --body "$(cat "$GITHUB_EVENT_PATH" | jq -r .pull_request.body)"
        env:
          GH_TOKEN: ${{ secrets.MY_PAT }}
