name: Rerun Failed Workflow

on:
  workflow_run:
    workflows:
      - "Auto Merge Approved PR"
    types:
      - completed

jobs:
  rerun:
    runs-on: ubuntu-latest
    if: ${{ (github.event.workflow_run.conclusion == 'failure') || (github.event.workflow_run.conclusion == 'cancelled') }}
    steps:
      - name: Rerun Workflow
        id: rerun_workflow
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const workflowName = 'Auto Merge Approved PR';
            const response = await octokit.rest.actions.reRunWorkflow({
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              run_id: ${{ github.event.workflow_run.id }},
            });

            if (response.status === 201) {
              return `Successfully triggered a rerun of the ${workflowName} workflow.`;
            } else {
              return `Failed to trigger a rerun of the ${workflowName} workflow.`;
            }
